//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_ship_H
#define METASPRITE_ship_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ship_TILE_ORIGIN 0
#define ship_TILE_W 8
#define ship_TILE_H 8
#define ship_WIDTH 1280
#define ship_HEIGHT 1152
#define ship_TILE_COUNT 4
#define ship_PALETTE_COUNT 1
#define ship_COLORS_PER_PALETTE 4
#define ship_TOTAL_COLORS 4
#define ship_MAP_ATTRIBUTES 0

BANKREF_EXTERN(ship)

extern const palette_color_t ship_palettes[4];
extern const uint8_t ship_tiles[64];

extern const unsigned char ship_map[23040];

#endif
