/*

 ADMIRAL_BENBOW_OUTSIDE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 90 x 90
   Tile set      : C:\Users\Brendan W Casey\Downloads\treasure_island\all_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define adm_ben_outWidth 90
#define adm_ben_outHeight 90
#define adm_ben_outBank 0

//extern unsigned char adm_ben_out[];
extern unsigned const char adm_ben_out[];

/* End of ADMIRAL_BENBOW_OUTSIDE.H */
