/*

 ALL_TILES_62_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 62

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define all_files_62_tilesBank 0
/* Start of tile array. */
//extern unsigned char all_tiles_62_tiles[];
extern unsigned const char all_tiles_62_tiles[];
/* End of ALL_FILES_62_TILES.H */
