/*

 ALL_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
//unsigned char all_tiles[] =
unsigned const char all_tiles[] =
{
  0xFF,0x00,0xFF,0x00,0xFE,0x00,0xFD,0x00,
  0xFF,0x00,0xFF,0x00,0xBF,0x00,0xFF,0x00
};

/* End of ALL_TILES.C */
