/*

 ALL_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define all_tilesBank 0
/* Start of tile array. */
//extern unsigned char all_tiles[];
extern unsigned const char all_tiles[];

/* End of ALL_TILES.H */
