/*

 GUY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 3
   Tile set      : C:\Users\Brendan W Casey\Downloads\treasure_island\sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define guy_spriteWidth 2
#define guy_spriteHeight 3
#define guy_spriteBank 0

extern unsigned char guy_sprite[];

/* End of GUY.H */
