/*

 TEST.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Brendan W Casey\Downloads\grass.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testWidth 40
#define testHeight 18
#define testBank 0

extern unsigned char map[];

/* End of TEST.H */
