/*

 JIM_HAWKINS_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 3
   Tile set      : sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define jim_hawkins_mapWidth 2
#define jim_hawkins_mapHeight 3
#define jim_hawkins_mapBank 0

unsigned const char jim_hawkins_map[] =
{
  0x04,0x05,0x02,0x03,0x06,0x07
};

/* End of JIM_HAWKINS_MAP.C */
