/*

 JIM_HAWKINS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 3
   Tile set      : sprite.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define jim_hawkins_mapWidth 2
#define jim_hawkins_mapHeight 3
#define jim_hawkins_mapBank 0

extern unsigned const char jim_hawkins_map[];

/* End of JIM_HAWKINS_MAP.H */
